---
- name: Configurar OSPFv3 en routers Cisco
  hosts: routers
  gather_facts: no
  vars:
    router_ids:
      R1: "1.1.1.1"
      R2: "2.2.2.2"
  tasks:
    # Crear proceso OSPFv3
    - name: Crear proceso OSPFv3
      uri:
        url: "https://{{ ansible_host }}/restconf/data/Cisco-IOS-XE-native:native/router/ospfv3=1"
        method: PUT
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        headers:
          Content-Type: "application/yang-data+json"
          Accept: "application/yang-data+json"
        body_format: json
        body:
          Cisco-IOS-XE-ospfv3:ospfv3:
            id: 1
        validate_certs: no
        status_code: [200, 201, 204]
      ignore_errors: yes

    # Configurar router-id
    - name: Configurar router-id OSPFv3
      uri:
        url: "https://{{ ansible_host }}/restconf/data/Cisco-IOS-XE-native:native/router/ospfv3=1"
        method: PATCH
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        headers:
          Content-Type: "application/yang-data+json"
          Accept: "application/yang-data+json"
        body_format: json
        body:
          Cisco-IOS-XE-ospfv3:ospfv3:
            router-id: "{{ router_ids[inventory_hostname] }}"
        validate_certs: no
        status_code: [200, 204]

    # Configurar OSPFv3 en la interfaz (estructura corregida)
    - name: Configurar OSPFv3 en interfaz GigabitEthernet2
      uri:
        url: "https://{{ ansible_host }}/restconf/data/Cisco-IOS-XE-native:native/interface/GigabitEthernet=2"
        method: PATCH
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        headers:
          Content-Type: "application/yang-data+json"
          Accept: "application/yang-data+json"
        body_format: json
        body:
          Cisco-IOS-XE-native:GigabitEthernet:
            Cisco-IOS-XE-ospfv3:ospfv3:
              process-id:
                - id: 1
                  ipv6:
                    area:
                      id: "0.0.0.0"  # ¡Corrección clave aquí!
        validate_certs: no
        status_code: [200, 204]

    # Verificación
    - name: Verificar configuración de interfaz
      uri:
        url: "https://{{ ansible_host }}/restconf/data/Cisco-IOS-XE-native:native/interface/GigabitEthernet=2"
        method: GET
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        headers:
          Accept: "application/yang-data+json"
        validate_certs: no
      register: interface_config
      ignore_errors: yes

    - name: Mostrar configuración de interfaz
      debug:
        var: interface_config.json
      when: interface_config.status == 200
